export const TODOS_REQUSET_LOADING = "TODOS_REQUSET_LOADING";
export const TODOS_REQUSET_SUCCESS = "TODOS_REQUSET_SUCCESS";
export const TODOS_REQUSET_ERROR = "TODOS_REQUSET_ERROR";
export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
